=== wollowizard/id2208-hw1/src/id2208/hw1/xml/employmentOfficeSchema.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.employmentSchema.com"
           xmlns="http://www.employmentSchema.com"
           elementFormDefault="qualified">
        
    <xsd:element name="employments" type="employmentsType"/>

    <xsd:complexType name="employmentsType">
        <xsd:sequence>
            <xsd:element name="person" type="personHistoryType" minOccurs="0" maxOccurs="unbounded" />
            
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="personHistoryType">
        <xsd:sequence>
            <xsd:element name="ssn" minOccurs="1" maxOccurs="1">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value="[0-9]{9}"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                                   
                </xsd:element>
            <xsd:element name="workExperiences" type="workExperiencesType" />
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="workExperiencesType">
        <xsd:sequence>
            <xsd:element name="workExperience" type="workExperienceType"  minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
        
  
    <xsd:complexType name="workExperienceType">
        <xsd:sequence>
            <xsd:element name="companyCode" type="companyCodeType"/>
            <xsd:element name="companyName" type="companyNameType"/>
            <xsd:element name="fromDate"  type="xsd:date"/>
            <xsd:element name="upToDate"  type="xsd:date"/>
            
        </xsd:sequence>        
    </xsd:complexType>
    
    <xsd:simpleType name="companyCodeType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]{5}" />
        </xsd:restriction>
    </xsd:simpleType>
    
    
    <xsd:simpleType name="companyNameType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Za-z]+"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    

</xsd:schema>

=== wollowizard/id2208-hw1/src/id2208/hw1/xml/employmentOffice.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<employments
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.employmentSchema.com'
    xsi:schemaLocation='http://www.employmentSchema.com employmentOfficeSchema.xsd'>
    <person>
        <ssn>123456789</ssn>
        
        <workExperiences>
            <workExperience>
                <companyCode>12345</companyCode>
                <companyName>KTH</companyName>
                <fromDate>2006-09-25</fromDate>
                <upToDate>2007-09-25</upToDate>
            </workExperience>
            
            <workExperience>
                <companyCode>54321</companyCode>
                <companyName>Ericsson</companyName>
                <fromDate>2008-09-25</fromDate>
                <upToDate>2009-09-25</upToDate>
            </workExperience>
        </workExperiences>
    </person>
    
    
    <person>
        <ssn>987654321</ssn>
        
        <workExperiences>
            <workExperience>
                <companyCode>12345</companyCode>
                <companyName>KTH</companyName>
                <fromDate>2006-09-25</fromDate>
                <upToDate>2007-09-25</upToDate>
            </workExperience>
            
            <workExperience>
                <companyCode>54321</companyCode>
                <companyName>Ericsson</companyName>
                <fromDate>2008-09-25</fromDate>
                <upToDate>2009-09-25</upToDate>
            </workExperience>
        </workExperiences>
    </person>
    

</employments>
