=== wollowizard/id2208-hw1/src/xml/companyInfoSchema.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.companyInfoSchema.net"
           xmlns="http://www.companyInfoSchema.net"
           elementFormDefault="qualified">
    <xs:element name="companyInfo" type="listCompaniesType"/>
    <xs:complexType name="listCompaniesType">
        <xs:sequence>
            <xs:element name="companyInfo" type="companyInfoType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="companyInfoType">
        <xs:sequence>
           <xs:element name="companyCode" type="companyCodeType" minOccurs="1" maxOccurs="1"/>
           <xs:element name="companyName" type="companyNameType" minOccurs="1" maxOccurs="1"/>
           <xs:element name="telefonNumber" type="telefonNumberType" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="companyCodeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{5}" />
        </xs:restriction>
    </xs:simpleType>
    
    
    <xs:simpleType name="companyNameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z]+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="telefonNumberType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{10}" />
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== wollowizard/id2208-hw1/src/xml/companyInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<ns1:companyInfo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://www.companyInfoSchema.net'
    xsi:schemaLocation='http://www.companyInfoSchema.net companyInfoSchema.xsd'>
    <ns1:companyInfo>
        <ns1:companyCode>12345</ns1:companyCode>
        <ns1:companyName>KTH</ns1:companyName>
        <ns1:telefonNumber>4687906000</ns1:telefonNumber>
    </ns1:companyInfo>
    
    <ns1:companyInfo>
        <ns1:companyCode>54321</ns1:companyCode>
        <ns1:companyName>Ericsson</ns1:companyName>
        <ns1:telefonNumber>4610719000</ns1:telefonNumber>
    </ns1:companyInfo>
    
    <ns1:companyInfo>
        <ns1:companyCode>22222</ns1:companyCode>
        <ns1:companyName>SU</ns1:companyName>
        <ns1:telefonNumber>4610719001</ns1:telefonNumber>
    </ns1:companyInfo>
    
    <ns1:companyInfo>
    
        <ns1:companyCode>11111</ns1:companyCode>
        <ns1:companyName>Microsoft</ns1:companyName>
        <ns1:telefonNumber>4610719002</ns1:telefonNumber>
    </ns1:companyInfo>
</ns1:companyInfo>
